name: Build server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: target cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release --verbose
      - name: Build and push docker container
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_IMAGE_TAG: "1.1.3"
        run: |

          docker build -t ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG} .
          docker tag ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG} ${DOCKER_IMAGE}:latest
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
          docker push ${DOCKER_IMAGE}:latest
